// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tweet.proto

package ir.sahab.nimroo.serialization;

public final class TweetProto {
  private TweetProto() {}
  public static void registerAllExtensions(
      com.github.os72.protobuf351.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.github.os72.protobuf351.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.github.os72.protobuf351.ExtensionRegistryLite) registry);
  }
  public interface TweetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Tweet)
      com.github.os72.protobuf351.MessageOrBuilder {

    /**
     * <code>required string user_name = 1;</code>
     */
    boolean hasUserName();
    /**
     * <code>required string user_name = 1;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>required string user_name = 1;</code>
     */
    com.github.os72.protobuf351.ByteString
        getUserNameBytes();

    /**
     * <code>required string text = 2;</code>
     */
    boolean hasText();
    /**
     * <code>required string text = 2;</code>
     */
    java.lang.String getText();
    /**
     * <code>required string text = 2;</code>
     */
    com.github.os72.protobuf351.ByteString
        getTextBytes();

    /**
     * <code>repeated string urls = 3;</code>
     */
    java.util.List<java.lang.String>
        getUrlsList();
    /**
     * <code>repeated string urls = 3;</code>
     */
    int getUrlsCount();
    /**
     * <code>repeated string urls = 3;</code>
     */
    java.lang.String getUrls(int index);
    /**
     * <code>repeated string urls = 3;</code>
     */
    com.github.os72.protobuf351.ByteString
        getUrlsBytes(int index);

    /**
     * <code>repeated string hash_tags = 4;</code>
     */
    java.util.List<java.lang.String>
        getHashTagsList();
    /**
     * <code>repeated string hash_tags = 4;</code>
     */
    int getHashTagsCount();
    /**
     * <code>repeated string hash_tags = 4;</code>
     */
    java.lang.String getHashTags(int index);
    /**
     * <code>repeated string hash_tags = 4;</code>
     */
    com.github.os72.protobuf351.ByteString
        getHashTagsBytes(int index);

    /**
     * <code>required string tweet_id = 5;</code>
     */
    boolean hasTweetId();
    /**
     * <code>required string tweet_id = 5;</code>
     */
    java.lang.String getTweetId();
    /**
     * <code>required string tweet_id = 5;</code>
     */
    com.github.os72.protobuf351.ByteString
        getTweetIdBytes();

    /**
     * <code>required string pub_date = 6;</code>
     */
    boolean hasPubDate();
    /**
     * <code>required string pub_date = 6;</code>
     */
    java.lang.String getPubDate();
    /**
     * <code>required string pub_date = 6;</code>
     */
    com.github.os72.protobuf351.ByteString
        getPubDateBytes();
  }
  /**
   * Protobuf type {@code Tweet}
   */
  public  static final class Tweet extends
      com.github.os72.protobuf351.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Tweet)
      TweetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Tweet.newBuilder() to construct.
    private Tweet(com.github.os72.protobuf351.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Tweet() {
      userName_ = "";
      text_ = "";
      urls_ = com.github.os72.protobuf351.LazyStringArrayList.EMPTY;
      hashTags_ = com.github.os72.protobuf351.LazyStringArrayList.EMPTY;
      tweetId_ = "";
      pubDate_ = "";
    }

    @java.lang.Override
    public final com.github.os72.protobuf351.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Tweet(
        com.github.os72.protobuf351.CodedInputStream input,
        com.github.os72.protobuf351.ExtensionRegistryLite extensionRegistry)
        throws com.github.os72.protobuf351.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.github.os72.protobuf351.UnknownFieldSet.Builder unknownFields =
          com.github.os72.protobuf351.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.github.os72.protobuf351.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              userName_ = bs;
              break;
            }
            case 18: {
              com.github.os72.protobuf351.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              text_ = bs;
              break;
            }
            case 26: {
              com.github.os72.protobuf351.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                urls_ = new com.github.os72.protobuf351.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              urls_.add(bs);
              break;
            }
            case 34: {
              com.github.os72.protobuf351.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                hashTags_ = new com.github.os72.protobuf351.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              hashTags_.add(bs);
              break;
            }
            case 42: {
              com.github.os72.protobuf351.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              tweetId_ = bs;
              break;
            }
            case 50: {
              com.github.os72.protobuf351.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              pubDate_ = bs;
              break;
            }
          }
        }
      } catch (com.github.os72.protobuf351.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.github.os72.protobuf351.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          urls_ = urls_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          hashTags_ = hashTags_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.github.os72.protobuf351.Descriptors.Descriptor
        getDescriptor() {
      return ir.sahab.nimroo.serialization.TweetProto.internal_static_Tweet_descriptor;
    }

    protected com.github.os72.protobuf351.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ir.sahab.nimroo.serialization.TweetProto.internal_static_Tweet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ir.sahab.nimroo.serialization.TweetProto.Tweet.class, ir.sahab.nimroo.serialization.TweetProto.Tweet.Builder.class);
    }

    private int bitField0_;
    public static final int USER_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object userName_;
    /**
     * <code>required string user_name = 1;</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string user_name = 1;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.github.os72.protobuf351.ByteString bs = 
            (com.github.os72.protobuf351.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string user_name = 1;</code>
     */
    public com.github.os72.protobuf351.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.github.os72.protobuf351.ByteString b = 
            com.github.os72.protobuf351.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.github.os72.protobuf351.ByteString) ref;
      }
    }

    public static final int TEXT_FIELD_NUMBER = 2;
    private volatile java.lang.Object text_;
    /**
     * <code>required string text = 2;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string text = 2;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.github.os72.protobuf351.ByteString bs = 
            (com.github.os72.protobuf351.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string text = 2;</code>
     */
    public com.github.os72.protobuf351.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.github.os72.protobuf351.ByteString b = 
            com.github.os72.protobuf351.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.github.os72.protobuf351.ByteString) ref;
      }
    }

    public static final int URLS_FIELD_NUMBER = 3;
    private com.github.os72.protobuf351.LazyStringList urls_;
    /**
     * <code>repeated string urls = 3;</code>
     */
    public com.github.os72.protobuf351.ProtocolStringList
        getUrlsList() {
      return urls_;
    }
    /**
     * <code>repeated string urls = 3;</code>
     */
    public int getUrlsCount() {
      return urls_.size();
    }
    /**
     * <code>repeated string urls = 3;</code>
     */
    public java.lang.String getUrls(int index) {
      return urls_.get(index);
    }
    /**
     * <code>repeated string urls = 3;</code>
     */
    public com.github.os72.protobuf351.ByteString
        getUrlsBytes(int index) {
      return urls_.getByteString(index);
    }

    public static final int HASH_TAGS_FIELD_NUMBER = 4;
    private com.github.os72.protobuf351.LazyStringList hashTags_;
    /**
     * <code>repeated string hash_tags = 4;</code>
     */
    public com.github.os72.protobuf351.ProtocolStringList
        getHashTagsList() {
      return hashTags_;
    }
    /**
     * <code>repeated string hash_tags = 4;</code>
     */
    public int getHashTagsCount() {
      return hashTags_.size();
    }
    /**
     * <code>repeated string hash_tags = 4;</code>
     */
    public java.lang.String getHashTags(int index) {
      return hashTags_.get(index);
    }
    /**
     * <code>repeated string hash_tags = 4;</code>
     */
    public com.github.os72.protobuf351.ByteString
        getHashTagsBytes(int index) {
      return hashTags_.getByteString(index);
    }

    public static final int TWEET_ID_FIELD_NUMBER = 5;
    private volatile java.lang.Object tweetId_;
    /**
     * <code>required string tweet_id = 5;</code>
     */
    public boolean hasTweetId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string tweet_id = 5;</code>
     */
    public java.lang.String getTweetId() {
      java.lang.Object ref = tweetId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.github.os72.protobuf351.ByteString bs = 
            (com.github.os72.protobuf351.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tweetId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string tweet_id = 5;</code>
     */
    public com.github.os72.protobuf351.ByteString
        getTweetIdBytes() {
      java.lang.Object ref = tweetId_;
      if (ref instanceof java.lang.String) {
        com.github.os72.protobuf351.ByteString b = 
            com.github.os72.protobuf351.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tweetId_ = b;
        return b;
      } else {
        return (com.github.os72.protobuf351.ByteString) ref;
      }
    }

    public static final int PUB_DATE_FIELD_NUMBER = 6;
    private volatile java.lang.Object pubDate_;
    /**
     * <code>required string pub_date = 6;</code>
     */
    public boolean hasPubDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string pub_date = 6;</code>
     */
    public java.lang.String getPubDate() {
      java.lang.Object ref = pubDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.github.os72.protobuf351.ByteString bs = 
            (com.github.os72.protobuf351.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pubDate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string pub_date = 6;</code>
     */
    public com.github.os72.protobuf351.ByteString
        getPubDateBytes() {
      java.lang.Object ref = pubDate_;
      if (ref instanceof java.lang.String) {
        com.github.os72.protobuf351.ByteString b = 
            com.github.os72.protobuf351.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pubDate_ = b;
        return b;
      } else {
        return (com.github.os72.protobuf351.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTweetId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPubDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.github.os72.protobuf351.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.github.os72.protobuf351.GeneratedMessageV3.writeString(output, 1, userName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.github.os72.protobuf351.GeneratedMessageV3.writeString(output, 2, text_);
      }
      for (int i = 0; i < urls_.size(); i++) {
        com.github.os72.protobuf351.GeneratedMessageV3.writeString(output, 3, urls_.getRaw(i));
      }
      for (int i = 0; i < hashTags_.size(); i++) {
        com.github.os72.protobuf351.GeneratedMessageV3.writeString(output, 4, hashTags_.getRaw(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.github.os72.protobuf351.GeneratedMessageV3.writeString(output, 5, tweetId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.github.os72.protobuf351.GeneratedMessageV3.writeString(output, 6, pubDate_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.github.os72.protobuf351.GeneratedMessageV3.computeStringSize(1, userName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.github.os72.protobuf351.GeneratedMessageV3.computeStringSize(2, text_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < urls_.size(); i++) {
          dataSize += computeStringSizeNoTag(urls_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getUrlsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < hashTags_.size(); i++) {
          dataSize += computeStringSizeNoTag(hashTags_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getHashTagsList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.github.os72.protobuf351.GeneratedMessageV3.computeStringSize(5, tweetId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.github.os72.protobuf351.GeneratedMessageV3.computeStringSize(6, pubDate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ir.sahab.nimroo.serialization.TweetProto.Tweet)) {
        return super.equals(obj);
      }
      ir.sahab.nimroo.serialization.TweetProto.Tweet other = (ir.sahab.nimroo.serialization.TweetProto.Tweet) obj;

      boolean result = true;
      result = result && (hasUserName() == other.hasUserName());
      if (hasUserName()) {
        result = result && getUserName()
            .equals(other.getUserName());
      }
      result = result && (hasText() == other.hasText());
      if (hasText()) {
        result = result && getText()
            .equals(other.getText());
      }
      result = result && getUrlsList()
          .equals(other.getUrlsList());
      result = result && getHashTagsList()
          .equals(other.getHashTagsList());
      result = result && (hasTweetId() == other.hasTweetId());
      if (hasTweetId()) {
        result = result && getTweetId()
            .equals(other.getTweetId());
      }
      result = result && (hasPubDate() == other.hasPubDate());
      if (hasPubDate()) {
        result = result && getPubDate()
            .equals(other.getPubDate());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUserName()) {
        hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getUserName().hashCode();
      }
      if (hasText()) {
        hash = (37 * hash) + TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getText().hashCode();
      }
      if (getUrlsCount() > 0) {
        hash = (37 * hash) + URLS_FIELD_NUMBER;
        hash = (53 * hash) + getUrlsList().hashCode();
      }
      if (getHashTagsCount() > 0) {
        hash = (37 * hash) + HASH_TAGS_FIELD_NUMBER;
        hash = (53 * hash) + getHashTagsList().hashCode();
      }
      if (hasTweetId()) {
        hash = (37 * hash) + TWEET_ID_FIELD_NUMBER;
        hash = (53 * hash) + getTweetId().hashCode();
      }
      if (hasPubDate()) {
        hash = (37 * hash) + PUB_DATE_FIELD_NUMBER;
        hash = (53 * hash) + getPubDate().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ir.sahab.nimroo.serialization.TweetProto.Tweet parseFrom(
        java.nio.ByteBuffer data)
        throws com.github.os72.protobuf351.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ir.sahab.nimroo.serialization.TweetProto.Tweet parseFrom(
        java.nio.ByteBuffer data,
        com.github.os72.protobuf351.ExtensionRegistryLite extensionRegistry)
        throws com.github.os72.protobuf351.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ir.sahab.nimroo.serialization.TweetProto.Tweet parseFrom(
        com.github.os72.protobuf351.ByteString data)
        throws com.github.os72.protobuf351.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ir.sahab.nimroo.serialization.TweetProto.Tweet parseFrom(
        com.github.os72.protobuf351.ByteString data,
        com.github.os72.protobuf351.ExtensionRegistryLite extensionRegistry)
        throws com.github.os72.protobuf351.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ir.sahab.nimroo.serialization.TweetProto.Tweet parseFrom(byte[] data)
        throws com.github.os72.protobuf351.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ir.sahab.nimroo.serialization.TweetProto.Tweet parseFrom(
        byte[] data,
        com.github.os72.protobuf351.ExtensionRegistryLite extensionRegistry)
        throws com.github.os72.protobuf351.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ir.sahab.nimroo.serialization.TweetProto.Tweet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.github.os72.protobuf351.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ir.sahab.nimroo.serialization.TweetProto.Tweet parseFrom(
        java.io.InputStream input,
        com.github.os72.protobuf351.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.github.os72.protobuf351.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ir.sahab.nimroo.serialization.TweetProto.Tweet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.github.os72.protobuf351.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ir.sahab.nimroo.serialization.TweetProto.Tweet parseDelimitedFrom(
        java.io.InputStream input,
        com.github.os72.protobuf351.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.github.os72.protobuf351.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ir.sahab.nimroo.serialization.TweetProto.Tweet parseFrom(
        com.github.os72.protobuf351.CodedInputStream input)
        throws java.io.IOException {
      return com.github.os72.protobuf351.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ir.sahab.nimroo.serialization.TweetProto.Tweet parseFrom(
        com.github.os72.protobuf351.CodedInputStream input,
        com.github.os72.protobuf351.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.github.os72.protobuf351.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ir.sahab.nimroo.serialization.TweetProto.Tweet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.github.os72.protobuf351.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Tweet}
     */
    public static final class Builder extends
        com.github.os72.protobuf351.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Tweet)
        ir.sahab.nimroo.serialization.TweetProto.TweetOrBuilder {
      public static final com.github.os72.protobuf351.Descriptors.Descriptor
          getDescriptor() {
        return ir.sahab.nimroo.serialization.TweetProto.internal_static_Tweet_descriptor;
      }

      protected com.github.os72.protobuf351.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ir.sahab.nimroo.serialization.TweetProto.internal_static_Tweet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ir.sahab.nimroo.serialization.TweetProto.Tweet.class, ir.sahab.nimroo.serialization.TweetProto.Tweet.Builder.class);
      }

      // Construct using ir.sahab.nimroo.serialization.TweetProto.Tweet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.github.os72.protobuf351.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.github.os72.protobuf351.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        urls_ = com.github.os72.protobuf351.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        hashTags_ = com.github.os72.protobuf351.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        tweetId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        pubDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.github.os72.protobuf351.Descriptors.Descriptor
          getDescriptorForType() {
        return ir.sahab.nimroo.serialization.TweetProto.internal_static_Tweet_descriptor;
      }

      public ir.sahab.nimroo.serialization.TweetProto.Tweet getDefaultInstanceForType() {
        return ir.sahab.nimroo.serialization.TweetProto.Tweet.getDefaultInstance();
      }

      public ir.sahab.nimroo.serialization.TweetProto.Tweet build() {
        ir.sahab.nimroo.serialization.TweetProto.Tweet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ir.sahab.nimroo.serialization.TweetProto.Tweet buildPartial() {
        ir.sahab.nimroo.serialization.TweetProto.Tweet result = new ir.sahab.nimroo.serialization.TweetProto.Tweet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.text_ = text_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          urls_ = urls_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.urls_ = urls_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          hashTags_ = hashTags_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.hashTags_ = hashTags_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000004;
        }
        result.tweetId_ = tweetId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000008;
        }
        result.pubDate_ = pubDate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.github.os72.protobuf351.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.github.os72.protobuf351.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.github.os72.protobuf351.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.github.os72.protobuf351.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.github.os72.protobuf351.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.github.os72.protobuf351.Message other) {
        if (other instanceof ir.sahab.nimroo.serialization.TweetProto.Tweet) {
          return mergeFrom((ir.sahab.nimroo.serialization.TweetProto.Tweet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ir.sahab.nimroo.serialization.TweetProto.Tweet other) {
        if (other == ir.sahab.nimroo.serialization.TweetProto.Tweet.getDefaultInstance()) return this;
        if (other.hasUserName()) {
          bitField0_ |= 0x00000001;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasText()) {
          bitField0_ |= 0x00000002;
          text_ = other.text_;
          onChanged();
        }
        if (!other.urls_.isEmpty()) {
          if (urls_.isEmpty()) {
            urls_ = other.urls_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureUrlsIsMutable();
            urls_.addAll(other.urls_);
          }
          onChanged();
        }
        if (!other.hashTags_.isEmpty()) {
          if (hashTags_.isEmpty()) {
            hashTags_ = other.hashTags_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureHashTagsIsMutable();
            hashTags_.addAll(other.hashTags_);
          }
          onChanged();
        }
        if (other.hasTweetId()) {
          bitField0_ |= 0x00000010;
          tweetId_ = other.tweetId_;
          onChanged();
        }
        if (other.hasPubDate()) {
          bitField0_ |= 0x00000020;
          pubDate_ = other.pubDate_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserName()) {
          return false;
        }
        if (!hasText()) {
          return false;
        }
        if (!hasTweetId()) {
          return false;
        }
        if (!hasPubDate()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.github.os72.protobuf351.CodedInputStream input,
          com.github.os72.protobuf351.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ir.sahab.nimroo.serialization.TweetProto.Tweet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.github.os72.protobuf351.InvalidProtocolBufferException e) {
          parsedMessage = (ir.sahab.nimroo.serialization.TweetProto.Tweet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object userName_ = "";
      /**
       * <code>required string user_name = 1;</code>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string user_name = 1;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.github.os72.protobuf351.ByteString bs =
              (com.github.os72.protobuf351.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string user_name = 1;</code>
       */
      public com.github.os72.protobuf351.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.github.os72.protobuf351.ByteString b = 
              com.github.os72.protobuf351.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.github.os72.protobuf351.ByteString) ref;
        }
      }
      /**
       * <code>required string user_name = 1;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string user_name = 1;</code>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string user_name = 1;</code>
       */
      public Builder setUserNameBytes(
          com.github.os72.protobuf351.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>required string text = 2;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string text = 2;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.github.os72.protobuf351.ByteString bs =
              (com.github.os72.protobuf351.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            text_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string text = 2;</code>
       */
      public com.github.os72.protobuf351.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.github.os72.protobuf351.ByteString b = 
              com.github.os72.protobuf351.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.github.os72.protobuf351.ByteString) ref;
        }
      }
      /**
       * <code>required string text = 2;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 2;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000002);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 2;</code>
       */
      public Builder setTextBytes(
          com.github.os72.protobuf351.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        text_ = value;
        onChanged();
        return this;
      }

      private com.github.os72.protobuf351.LazyStringList urls_ = com.github.os72.protobuf351.LazyStringArrayList.EMPTY;
      private void ensureUrlsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          urls_ = new com.github.os72.protobuf351.LazyStringArrayList(urls_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string urls = 3;</code>
       */
      public com.github.os72.protobuf351.ProtocolStringList
          getUrlsList() {
        return urls_.getUnmodifiableView();
      }
      /**
       * <code>repeated string urls = 3;</code>
       */
      public int getUrlsCount() {
        return urls_.size();
      }
      /**
       * <code>repeated string urls = 3;</code>
       */
      public java.lang.String getUrls(int index) {
        return urls_.get(index);
      }
      /**
       * <code>repeated string urls = 3;</code>
       */
      public com.github.os72.protobuf351.ByteString
          getUrlsBytes(int index) {
        return urls_.getByteString(index);
      }
      /**
       * <code>repeated string urls = 3;</code>
       */
      public Builder setUrls(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUrlsIsMutable();
        urls_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string urls = 3;</code>
       */
      public Builder addUrls(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUrlsIsMutable();
        urls_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string urls = 3;</code>
       */
      public Builder addAllUrls(
          java.lang.Iterable<java.lang.String> values) {
        ensureUrlsIsMutable();
        com.github.os72.protobuf351.AbstractMessageLite.Builder.addAll(
            values, urls_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string urls = 3;</code>
       */
      public Builder clearUrls() {
        urls_ = com.github.os72.protobuf351.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string urls = 3;</code>
       */
      public Builder addUrlsBytes(
          com.github.os72.protobuf351.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUrlsIsMutable();
        urls_.add(value);
        onChanged();
        return this;
      }

      private com.github.os72.protobuf351.LazyStringList hashTags_ = com.github.os72.protobuf351.LazyStringArrayList.EMPTY;
      private void ensureHashTagsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          hashTags_ = new com.github.os72.protobuf351.LazyStringArrayList(hashTags_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string hash_tags = 4;</code>
       */
      public com.github.os72.protobuf351.ProtocolStringList
          getHashTagsList() {
        return hashTags_.getUnmodifiableView();
      }
      /**
       * <code>repeated string hash_tags = 4;</code>
       */
      public int getHashTagsCount() {
        return hashTags_.size();
      }
      /**
       * <code>repeated string hash_tags = 4;</code>
       */
      public java.lang.String getHashTags(int index) {
        return hashTags_.get(index);
      }
      /**
       * <code>repeated string hash_tags = 4;</code>
       */
      public com.github.os72.protobuf351.ByteString
          getHashTagsBytes(int index) {
        return hashTags_.getByteString(index);
      }
      /**
       * <code>repeated string hash_tags = 4;</code>
       */
      public Builder setHashTags(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHashTagsIsMutable();
        hashTags_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hash_tags = 4;</code>
       */
      public Builder addHashTags(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHashTagsIsMutable();
        hashTags_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hash_tags = 4;</code>
       */
      public Builder addAllHashTags(
          java.lang.Iterable<java.lang.String> values) {
        ensureHashTagsIsMutable();
        com.github.os72.protobuf351.AbstractMessageLite.Builder.addAll(
            values, hashTags_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hash_tags = 4;</code>
       */
      public Builder clearHashTags() {
        hashTags_ = com.github.os72.protobuf351.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hash_tags = 4;</code>
       */
      public Builder addHashTagsBytes(
          com.github.os72.protobuf351.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHashTagsIsMutable();
        hashTags_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object tweetId_ = "";
      /**
       * <code>required string tweet_id = 5;</code>
       */
      public boolean hasTweetId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string tweet_id = 5;</code>
       */
      public java.lang.String getTweetId() {
        java.lang.Object ref = tweetId_;
        if (!(ref instanceof java.lang.String)) {
          com.github.os72.protobuf351.ByteString bs =
              (com.github.os72.protobuf351.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tweetId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string tweet_id = 5;</code>
       */
      public com.github.os72.protobuf351.ByteString
          getTweetIdBytes() {
        java.lang.Object ref = tweetId_;
        if (ref instanceof String) {
          com.github.os72.protobuf351.ByteString b = 
              com.github.os72.protobuf351.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tweetId_ = b;
          return b;
        } else {
          return (com.github.os72.protobuf351.ByteString) ref;
        }
      }
      /**
       * <code>required string tweet_id = 5;</code>
       */
      public Builder setTweetId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        tweetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string tweet_id = 5;</code>
       */
      public Builder clearTweetId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        tweetId_ = getDefaultInstance().getTweetId();
        onChanged();
        return this;
      }
      /**
       * <code>required string tweet_id = 5;</code>
       */
      public Builder setTweetIdBytes(
          com.github.os72.protobuf351.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        tweetId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pubDate_ = "";
      /**
       * <code>required string pub_date = 6;</code>
       */
      public boolean hasPubDate() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string pub_date = 6;</code>
       */
      public java.lang.String getPubDate() {
        java.lang.Object ref = pubDate_;
        if (!(ref instanceof java.lang.String)) {
          com.github.os72.protobuf351.ByteString bs =
              (com.github.os72.protobuf351.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pubDate_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string pub_date = 6;</code>
       */
      public com.github.os72.protobuf351.ByteString
          getPubDateBytes() {
        java.lang.Object ref = pubDate_;
        if (ref instanceof String) {
          com.github.os72.protobuf351.ByteString b = 
              com.github.os72.protobuf351.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pubDate_ = b;
          return b;
        } else {
          return (com.github.os72.protobuf351.ByteString) ref;
        }
      }
      /**
       * <code>required string pub_date = 6;</code>
       */
      public Builder setPubDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        pubDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string pub_date = 6;</code>
       */
      public Builder clearPubDate() {
        bitField0_ = (bitField0_ & ~0x00000020);
        pubDate_ = getDefaultInstance().getPubDate();
        onChanged();
        return this;
      }
      /**
       * <code>required string pub_date = 6;</code>
       */
      public Builder setPubDateBytes(
          com.github.os72.protobuf351.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        pubDate_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.github.os72.protobuf351.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.github.os72.protobuf351.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Tweet)
    }

    // @@protoc_insertion_point(class_scope:Tweet)
    private static final ir.sahab.nimroo.serialization.TweetProto.Tweet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ir.sahab.nimroo.serialization.TweetProto.Tweet();
    }

    public static ir.sahab.nimroo.serialization.TweetProto.Tweet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.github.os72.protobuf351.Parser<Tweet>
        PARSER = new com.github.os72.protobuf351.AbstractParser<Tweet>() {
      public Tweet parsePartialFrom(
          com.github.os72.protobuf351.CodedInputStream input,
          com.github.os72.protobuf351.ExtensionRegistryLite extensionRegistry)
          throws com.github.os72.protobuf351.InvalidProtocolBufferException {
        return new Tweet(input, extensionRegistry);
      }
    };

    public static com.github.os72.protobuf351.Parser<Tweet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.os72.protobuf351.Parser<Tweet> getParserForType() {
      return PARSER;
    }

    public ir.sahab.nimroo.serialization.TweetProto.Tweet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.github.os72.protobuf351.Descriptors.Descriptor
    internal_static_Tweet_descriptor;
  private static final 
    com.github.os72.protobuf351.GeneratedMessageV3.FieldAccessorTable
      internal_static_Tweet_fieldAccessorTable;

  public static com.github.os72.protobuf351.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.github.os72.protobuf351.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013tweet.proto\"m\n\005Tweet\022\021\n\tuser_name\030\001 \002(" +
      "\t\022\014\n\004text\030\002 \002(\t\022\014\n\004urls\030\003 \003(\t\022\021\n\thash_ta" +
      "gs\030\004 \003(\t\022\020\n\010tweet_id\030\005 \002(\t\022\020\n\010pub_date\030\006" +
      " \002(\tB+\n\035ir.sahab.nimroo.serializationB\nT" +
      "weetProto"
    };
    com.github.os72.protobuf351.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.github.os72.protobuf351.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.github.os72.protobuf351.ExtensionRegistry assignDescriptors(
              com.github.os72.protobuf351.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.github.os72.protobuf351.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.github.os72.protobuf351.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Tweet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Tweet_fieldAccessorTable = new
      com.github.os72.protobuf351.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Tweet_descriptor,
        new java.lang.String[] { "UserName", "Text", "Urls", "HashTags", "TweetId", "PubDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
